<?php
$uni = array(
'Abertay University',
'Aberystwyth University',
'AECC University College',
'Anglia Ruskin University',
'Arden University',
'Aston University',
'Bangor University',
'Bath Spa University',
'Birkbeck',
'Birmingham City University',
'Bishop Grosseteste University',
'Bournemouth University',
'BPP University',
'Brunel University',
'Buckinghamshire New University',
'Canterbury Christ Church University',
'Cardiff Metropolitan University',
'Cardiff University',
'City',
'Courtauld Institute of Art',
'Coventry University',
'Cranfield University',
'De Montfort University',
'Durham University',
'Edge Hill University',
'Edinburgh Napier University',
'Falmouth University',
'Glasgow Caledonian University',
'Goldsmiths',
'Harper Adams University',
'Hartpury University',
'Heriot-Watt University',
'Imperial College London',
'Institute of Cancer Research',
'Keele University',
'King\'s College London',
'Kingston University',
'Lancaster University',
'Leeds Arts University',
'Leeds Beckett University',
'Leeds Trinity University',
'Liverpool Hope University',
'Liverpool John Moores University',
'London Business School',
'London Institute of Banking and Finance',
'London Metropolitan University',
'London School of Economics and Political Science',
'London School of Hygiene and Tropical Medicine',
'London South Bank University',
'Loughborough University',
'Manchester Metropolitan University',
'Middlesex University',
'Newcastle University',
'Newman University',
'Northumbria University',
'Norwich University of the Arts',
'Nottingham Trent University',
'Oxford Brookes University',
'Plymouth Marjon University',
'Queen Margaret University',
'Queen Mary',
'Queen\'s University Belfast',
'Ravensbourne University London',
'Regent\'s University London',
'Roehampton University',
'Royal Academy of Music',
'Royal Agricultural University',
'Royal Central School of Speech and Drama',
'Royal Holloway',
'Royal Veterinary College',
'School of Oriental and African Studies',
'Sheffield Hallam University',
'Solent University',
'St George\'s',
'St Mary\'s University',
'Staffordshire University',
'Swansea University',
'Teesside University',
'The Arts University Bournemouth',
'The Open University',
'The Robert Gordon University',
'Ulster University',
'University College Birmingham',
'University College London',
'University College of Estate Management',
'University College of Osteopathy',
'University for the Creative Arts',
'University of Aberdeen',
'University of Bath',
'University of Bedfordshire',
'University of Birmingham',
'University of Bolton',
'University of Bradford',
'University of Brighton',
'University of Bristol',
'University of Buckingham',
'University of Cambridge',
'University of Central Lancashire',
'University of Chester',
'University of Chichester',
'University of Cumbria',
'University of Derby',
'University of Dundee',
'University of East Anglia',
'University of East London',
'University of Edinburgh',
'University of Essex',
'University of Exeter',
'University of Glasgow',
'University of Gloucestershire',
'University of Greenwich',
'University of Hertfordshire',
'University of Huddersfield',
'University of Hull',
'University of Kent',
'University of Law',
'University of Leeds',
'University of Leicester',
'University of Lincoln',
'University of Liverpool',
'University of London',
'University of Manchester',
'University of Northampton',
'University of Nottingham',
'University of Oxford',
'University of Plymouth',
'University of Portsmouth',
'University of Reading',
'University of Salford',
'University of Sheffield',
'University of South Wales',
'University of Southampton',
'University of St Andrews',
'University of Stirling',
'University of Strathclyde',
'University of Suffolk',
'University of Sunderland',
'University of Surrey',
'University of Sussex',
'University of the Arts London',
'University of the Highlands & Islands',
'University of the West of England',
'University of the West of Scotland',
'University of Ulster',
'University of Wales',
'University of Warwick',
'University of West London',
'University of Westminster',
'University of Winchester',
'University of Wolverhampton',
'University of Worcester',
'University of York',
'Wrexham Glyndŵr University',
'Writtle University College',
'York St John University',
);
?>